### ISSUE TITLE
Create a release/tag not including the twig extensions version bump

### ISSUE THREAD

**Issue by jdubuisson** [symfony2admingenerator/AvocodeFormExtensionsBundle#164]
Hi,

The last PR updated the composer.json file. Could you tag/release the project without this change ? 0.1.5 is getting old, a requirement change seems to be a good reason to tag.

Unless I'm mistaken, when trying to target a specific commit (to avoid twig/extensions 1.2), the dev-master requirements are applied. Thus preventing anyone from getting an updated version without twig/extensions 1.2.

Is d0d07ae good candidate to be 0.1.6 ?

**Comment by loostro** [comment]
Done

**Comment by jdubuisson** [comment]
Thanks !
