### ISSUE TITLE
Select2 not working when editing

### ISSUE THREAD

**Issue by vkosachev** [symfony2admingenerator/AvocodeFormExtensionsBundle#169]
Seems that select2 is not triggered to be rendered when I edit an entity with `afe_select2_entity` type. JS and CSS are present on page, but it renders like a simple select.

**Comment by vkosachev** [comment]
Found a solution, it seems that if you use something else than word "form" in your template.. it will not render.

**Comment by bobvandevijver** [comment]
Do you mean that you do not use `form` as the form variable? If you want to do that, you will have to include the following somewhere in your header tag:

``` twig
{{ form_css(form_variable) }}
{{ form_js(form_variable) }}
```
