### ISSUE TITLE
Failed to load resource: 

### ISSUE THREAD

**Issue by atrimech** [symfony2admingenerator/AvocodeFormExtensionsBundle#170]
Hi all,

I have a issue with this bundle, on my localhost, it's work perfectly, but on my server, i have all this javascript problem : "Failed to load resource ..."

Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_double-list_5.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_datepicker_3.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_daterangepicker_4.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_select2_7.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_single-upload_8.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_timepicker_10.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_jquery.minicolors_6.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_filetypeicons_9.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/blueimp.jquery-file-upload.min_tmpl_1.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/blueimp.jquery-file-upload.min_load-image-meta_5.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/blueimp.jquery-file-upload.min_load-image_2.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_bootstrap-collection_1.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/blueimp.jquery-file-upload.min_load-image-exif_6.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/blueimp.jquery-file-upload.min_canvas-to-blob_8.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/blueimp.jquery-file-upload.min_jquery.fileupload_10.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/blueimp.jquery-file-upload.min_jquery.iframe-transport_9.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/blueimp.jquery-file-upload.min_load-image-ios_3.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/blueimp.jquery-file-upload.min_load-image-exif-map_7.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/blueimp.jquery-file-upload.min_jquery.fileupload-ui_14.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/blueimp.jquery-file-upload.min_jquery.fileupload-process_11.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/form-extensions.min_collection-upload_2.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/form-extensions.min_bootstrap-collection_1.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/blueimp.jquery-file-upload.min_jquery.fileupload-image_12.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/blueimp.jquery-file-upload.min_jquery.fileupload-validate_13.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/form-extensions.min_daterangepicker_5.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/form-extensions.min_jquery.knob_7.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/form-extensions.min_double-list_6.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/form-extensions.min_date_4.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/blueimp.jquery-file-upload.min_load-image-orientation_4.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/form-extensions.min_single-upload_10.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/form-extensions.min_select2_9.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/form-extensions.min_bootstrap-timepicker_11.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/form-extensions.min_jquery.elastic_12.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/form-extensions.min_datepicker_3.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/js/compiled/avocodeformextensions/form-extensions.min_jquery.minicolors_8.js Failed to load resource: the server responded with a status of 404 (Not Found)
select2_locale_fr.js:7 Uncaught TypeError: Cannot read property 'defaults' of undefined
bootstrap-datepicker.fr.js:6 Uncaught TypeError: Cannot set property 'fr' of undefined
new:589 Uncaught TypeError: $field.select2 is not a function
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_collection-upload_2.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_double-list_5.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_bootstrap-collection_1.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_jquery.minicolors_6.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_select2_7.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_daterangepicker_4.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_single-upload_8.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_timepicker_10.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://myserver.com/assetic/css/compiled/avocodeformextensions/form-extensions.min_datepicker_3.css Failed to load resource: the server responded with a status of 404 (Not Found)

Thank you

**Comment by ioleo** [comment]
This is definately a problem with your server config.

**Comment by atrimech** [comment]
I solved the problem ;)

i forget to import js and css files on my edit layout
Thanks,
